name: Generate Redacted Briefing

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-brief:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install fpdf --quiet

    - name: Ensure output directory exists
      run: mkdir -p docs/intel

    - name: Run briefing script
      run: python3 scripts/brief_generator.py

    - name: Commit redacted brief
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add docs/intel/brief-auto.pdf
        git commit -m "Auto: update redacted brief"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
