# .github/workflows/briefing.yml
name: Generate Redacted Briefing

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install fpdf

    - name: Ensure output folder exists
      run: mkdir -p docs/intel

    - name: Run briefing generator
      run: python scripts/brief_generator.py

    - name: Commit PDF if changed
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add docs/intel/brief-auto.pdf
        git diff --cached --quiet || git commit -m "Auto-update: redacted briefing"
        git push
