name: 📚 Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - fix/deception-modules-cleanup

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autodoc-typehints

      - name: 🛠 Build HTML docs
        run: |
          cd docs
          make html

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
