name: LUNE :: Ops CI
on: [push, pull_request]
jobs:
  ops-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 bandit
      - name: Lint Check
        run: flake8 lune/
      - name: Security Scan
        run: bandit -r lune/
