name: Ops Intel
on:
  push:
    paths:
      - 'scripts/signal_injector.py'
      - 'decoys.json'
jobs:
  deception-signal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Inject Deception Signals
        run: |
          python scripts/signal_injector.py
