name: Ops Intel Enrichment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  recon:
    runs-on: ubuntu-latest
    env:
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
      SHODAN_API_KEY: ${{ secrets.SHODAN_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run recon engine
        run: |
          python scripts/recon_engine.py

      - name: Upload Recon Report
        uses: actions/upload-artifact@v3
        with:
          name: recon-report
          path: docs/intel/recon_report.pdf