name: Ops Intel

on:
  push:
    paths:
      - 'scripts/**'
      - 'decoys.json'
      - '.github/workflows/**'

jobs:
  tripwire-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Simulate Tripwire Monitor
        run: |
          python3 scripts/tripwire_monitor.py